name: Terraform Apply

on:
  workflow_dispatch:
  push:
    branches:
      - devel
      - stage
      - prod
    paths:
      - 'terraform/**'

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Select Terraform workspace
        run: terraform workspace select ${{ github.ref_name }} || terraform workspace new ${{ github.ref_name }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=environments/${{ github.ref_name }}.tfvars
